"""replace_category_and_flavor_with_texture

Revision ID: 00a79d5e0390
Revises: a8181571ddcd
Create Date: 2026-05-12 10:49:19.946878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a79d5e0390'
down_revision: Union[str, Sequence[str], None] = 'a8181571ddcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('texture', sa.String(length=100), nullable=True))
    op.drop_column('dishes', 'flavor_type')
    op.drop_column('dishes', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('flavor_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('dishes', 'texture')
    # ### end Alembic commands ###
