"""add back bank details and last_name to restaurants

Revision ID: 892ca80a1a81
Revises: 00a79d5e0390
Create Date: 2026-05-12 11:08:06.838009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892ca80a1a81'
down_revision: Union[str, Sequence[str], None] = '00a79d5e0390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('account_holder_name', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('account_number', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('ifsc_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'ifsc_code')
    op.drop_column('restaurants', 'account_number')
    op.drop_column('restaurants', 'account_holder_name')
    op.drop_column('restaurants', 'bank_name')
    op.drop_column('restaurants', 'last_name')
    # ### end Alembic commands ###
