"""add_meal_time_to_dishes

Revision ID: a8181571ddcd
Revises: abcaf979d3cc
Create Date: 2026-05-12 10:39:08.174799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8181571ddcd'
down_revision: Union[str, Sequence[str], None] = 'abcaf979d3cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('meal_time', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'meal_time')
    # ### end Alembic commands ###
