"""update dish and restaurant fields

Revision ID: abcaf979d3cc
Revises: 16cd2d49992a
Create Date: 2026-05-11 13:48:55.754356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abcaf979d3cc'
down_revision: Union[str, Sequence[str], None] = '16cd2d49992a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('meal_type', sa.String(length=100), nullable=True))
    op.add_column('dishes', sa.Column('flavor_type', sa.String(length=100), nullable=True))
    op.add_column('dishes', sa.Column('dietary_type', sa.String(length=100), nullable=True))
    op.add_column('dishes', sa.Column('spicy', sa.Boolean(), nullable=True))
    op.alter_column('dishes', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('dishes', 'rating')
    op.drop_column('dishes', 'cost_price')
    op.drop_column('dishes', 'delivery')
    op.drop_column('dishes', 'created_at')
    op.drop_column('dishes', 'discounted_price')
    op.drop_column('dishes', 'date_added')
    op.drop_column('dishes', 'description')
    op.drop_column('dishes', 'return_policy')
    op.drop_column('dishes', 'featured_week')
    op.drop_column('dishes', 'short_description')
    op.drop_column('dishes', 'preparation_time_minutes')
    op.drop_column('dishes', 'expiry_date')
    op.drop_column('dishes', 'is_deleted')
    op.drop_column('dishes', 'selling_price')
    op.drop_column('dishes', 'cuisine_id')
    op.drop_column('dishes', 'quantity')
    op.drop_column('dishes', 'is_featured')
    op.drop_column('dishes', 'add_discount')
    op.drop_column('restaurants', 'latitude')
    op.drop_column('restaurants', 'created_at')
    op.drop_column('restaurants', 'address_line')
    op.drop_column('restaurants', 'ifsc_code')
    op.drop_column('restaurants', 'is_active')
    op.drop_column('restaurants', 'is_deleted')
    op.drop_column('restaurants', 'account_holder_name')
    op.drop_column('restaurants', 'updated_at')
    op.drop_column('restaurants', 'delivery_radius_km')
    op.drop_column('restaurants', 'bank_name')
    op.drop_column('restaurants', 'price_level')
    op.drop_column('restaurants', 'postal_code')
    op.drop_column('restaurants', 'rating')
    op.drop_column('restaurants', 'first_name')
    op.drop_column('restaurants', 'account_number')
    op.drop_column('restaurants', 'state')
    op.drop_column('restaurants', 'last_name')
    op.drop_column('restaurants', 'longitude')
    op.drop_column('restaurants', 'birth_date')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('user', 'admin', 'superadmin', name='userrole'),
               nullable=False,
               postgresql_using="role::userrole")
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'profile_status')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'notification_preferences')
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'signup_type')
    op.drop_column('users', 'spice_level_preference')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'analytics_data')
    op.drop_column('users', 'survey_completed_at')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'password')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'device_info')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'apple_id')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'activity_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activity_log', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('apple_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('device_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_premium', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('survey_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('analytics_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('spice_level_preference', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('signup_type', sa.VARCHAR(length=20), server_default=sa.text("'email'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_staff', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('notification_preferences', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_status', sa.VARCHAR(length=30), server_default=sa.text("'pending_verification'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('user', 'admin', 'superadmin', name='userrole'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.add_column('restaurants', sa.Column('birth_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('account_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('price_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('delivery_radius_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('account_holder_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('ifsc_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('address_line', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('add_discount', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('cuisine_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('selling_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('preparation_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('short_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('featured_week', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('return_policy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('date_added', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('discounted_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('delivery', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('cost_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('dishes', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('dishes', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('dishes', 'spicy')
    op.drop_column('dishes', 'dietary_type')
    op.drop_column('dishes', 'flavor_type')
    op.drop_column('dishes', 'meal_type')
    # ### end Alembic commands ###
