"""add_latitude_longitude_to_restaurants

Revision ID: bfe21b817a41
Revises: 6047f974f09a
Create Date: 2026-05-20 16:52:03.839732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe21b817a41'
down_revision: Union[str, Sequence[str], None] = '6047f974f09a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'longitude')
    op.drop_column('restaurants', 'latitude')
    # ### end Alembic commands ###
