"""add birth_date to restaurants

Revision ID: e5e3326f5f1e
Revises: 892ca80a1a81
Create Date: 2026-05-12 11:11:10.617950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e3326f5f1e'
down_revision: Union[str, Sequence[str], None] = '892ca80a1a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('birth_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'birth_date')
    # ### end Alembic commands ###
